name: grocery_planner_app
description: "A Flutter app for grocery planning and budget management."

# Prevents the package from being accidentally published to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Routing
  go_router: ^15.1.2

  # Local storage
  floor: ^1.4.2
  shared_preferences: ^2.2.1

  # Network
  dio: ^5.3.2
  connectivity_plus: ^6.1.4

  # Dependency injection
  get_it: ^8.0.3

  # Functional programming
  dartz: ^0.10.1

  # UI
  flutter_svg: ^2.0.7
  intl: ^0.20.2

  # Utils
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.6
  bloc_test: ^10.0.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
